"""LLM-as-judge scoring for text samples generated by each optimizer's trained model.

This is the "using an LLM API" half of main/run_llm_optimizer_benchmark.py: the
optimizers themselves are trained locally (a hosted LLM API gives no gradient
access, so it cannot sit inside a custom torch.optim.Optimizer's step()), but
once each optimizer has produced a small trained character-level model, its
generated text samples are blind-scored by a free-tier Hugging Face Inference
Providers chat model, as a qualitative complement to the quantitative
loss/perplexity metrics already computed locally. This needs only a free
Hugging Face account token -- no local model download, no billing.
"""

from __future__ import annotations

import json
import os
import random
import re

from huggingface_hub import InferenceClient

DEFAULT_JUDGE_MODEL = "Qwen/Qwen2.5-7B-Instruct"


class MissingAPIKeyError(RuntimeError):
    """Raised when HF_TOKEN is not set and no token was passed explicitly."""


def _extract_json_object(text: str) -> dict:
    """Best-effort extraction of a JSON object from a free-tier model's reply.

    Small/free instruct models don't always honor response_format strictly, so
    this pulls the first top-level {...} block rather than requiring the
    entire reply to be pure JSON.
    """
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"no JSON object found in judge response: {text!r}")
    return json.loads(match.group(0))


def judge_samples(
    samples: dict[str, str],
    corpus_excerpt: str,
    token: str | None = None,
    model: str = DEFAULT_JUDGE_MODEL,
) -> dict[str, dict]:
    """Blind-score each optimizer's generated text sample via a free HF Inference model.

    Sample identities are shuffled and relabeled before being sent, so the
    judge cannot use the optimizer name itself as a signal.

    Returns {optimizer_name: {"coherence_score": int, "style_fidelity_score": int, "rationale": str}}.
    Raises MissingAPIKeyError if no token is available.
    """
    key = token or os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_TOKEN")
    if not key:
        raise MissingAPIKeyError(
            "HF_TOKEN is not set. Create a free token at https://huggingface.co/settings/tokens "
            "and export it, or pass --skip-judge to run the benchmark without it."
        )

    client = InferenceClient(model=model, token=key, provider="auto")

    names = list(samples.keys())
    shuffled = names[:]
    random.Random(0).shuffle(shuffled)
    labels = {name: f"sample_{chr(97 + i)}" for i, name in enumerate(shuffled)}
    reverse_labels = {label: name for name, label in labels.items()}

    blind_block = "\n\n".join(f"[{labels[name]}]\n{samples[name]}" for name in shuffled)

    prompt = (
        "You are judging short text completions generated by small character-level "
        "language models trained on the following corpus excerpt:\n\n"
        f"{corpus_excerpt}\n\n"
        "Score each sample below on two 1-10 axes: coherence (fluency, grammaticality, "
        "local sensibility) and style_fidelity (resemblance to the corpus's register, "
        "vocabulary, and structure). These are small models trained briefly on limited "
        "compute -- expect low absolute scores, and focus on ranking the samples "
        "relative to each other. You are not told which training method produced "
        "which sample.\n\n"
        f"{blind_block}\n\n"
        "Respond with ONLY a single JSON object, no other text, in this exact shape:\n"
        "{"
        + ", ".join(
            f'"{label}": {{"coherence_score": <int 1-10>, "style_fidelity_score": <int 1-10>, "rationale": "<short string>"}}'
            for label in labels.values()
        )
        + "}"
    )

    response = client.chat_completion(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1024,
        temperature=0.0,
    )
    reply_text = response.choices[0].message.content
    parsed = _extract_json_object(reply_text)
    return {reverse_labels[label]: scores for label, scores in parsed.items() if label in reverse_labels}
